import { ThemeProvider } from '@/components/theme-provider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ToggleMode } from '@/components/toggle-mode'
import Header from '@/components/Header'
import { SideBarProvider } from '@/contexts/SideBarContext'
import SideBar from '@/components/SideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={`${inter.className} flex`}>
				<ThemeProvider attribute="class" defaultTheme="system">
					<div className="fixed bottom-4 right-4">
						<ToggleMode />
					</div>
					<SideBarProvider>
						<>
							<SideBar />
							<main className="mx-auto max-w-7xl">
								<Header />
								{children}
							</main>
						</>
					</SideBarProvider>
				</ThemeProvider>
			</body>
		</html>
	)
}
