import { ThemeProvider } from '@/components/theme-provider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ToggleMode } from '@/components/toggle-mode'
import SideBar from '@/components/SideBar'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={`${inter.className} flex`}>
				<ThemeProvider attribute="class" defaultTheme="system">
					<div className="fixed bottom-4 right-4">
						<ToggleMode />
					</div>
					<SideBar />
					<main className="grid w-full grid-cols-1 lg:grid-cols-12">
						<div className="col-start-2  col-end-12 px-4 ">
							<Header />
							{children}
						</div>
					</main>
				</ThemeProvider>
			</body>
		</html>
	)
}
